In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("500_Person_Gender_Height_Weight_Index.csv")

In [3]:
data

Gender  Height  Weight  Index
0      Male     174      96      4
1      Male     189      87      2
2    Female     185     110      4
3    Female     195     104      3
4      Male     149      61      3
..      ...     ...     ...    ...
495  Female     150     153      5
496  Female     184     121      4
497  Female     141     136      5
498    Male     150      95      5
499    Male     173     131      5

[500 rows x 4 columns]

In [5]:
height_cm=[174,189,185,195,140,150,184,141,150,173]
np_height_cm=np.array(height_cm)
print(np_height_cm)

[174 189 185 195 140 150 184 141 150 173]


In [6]:
weight_lb=[96,87,110,104,61,153,121,136,95,131]
np_weight_lb=np.array(weight_lb)
print(np_weight_lb)

[ 96  87 110 104  61 153 121 136  95 131]


In [7]:
np_weight_kg=np_weight_lb/2.205
print(np_weight_kg)

[43.53741497 39.45578231 49.88662132 47.16553288 27.66439909 69.3877551
 54.87528345 61.67800454 43.08390023 59.41043084]


In [8]:
np_height_cm=np.array(height_cm)
np_weight_kg=np.array(weight_lb)/2.205
bmi=np_weight_kg/np_height_m**2*10000
print(bmi)

[14.38017405 11.04554249 14.57607635 12.40382193 14.11448933 30.83900227
 16.20843675 31.02359264 19.1484001  19.85045636]


In [11]:
np_height_cm=np.array(height_cm)
print(np_height_cm.shape)

(10,)


In [12]:
np_data=np.array(data)
print(np_data[10,:])

['Male' 195 81 2]


In [14]:
np_height_cm=np.array(height_cm)
print(np.mean(np_height_cm))

168.1


In [15]:
print(np.median(np_height_cm))

173.5


In [16]:
np_2d=np.array([[174,189,185,195],[97,87,110,104]])
np_2d

array([[174, 189, 185, 195],
       [ 97,  87, 110, 104]])

In [17]:
np_2d.shape

(2, 4)

In [18]:
height=[174,189,18,195]
np.mean(height)

144.0

In [19]:
height=[174,189,18,195]
np.median(height)

181.5

In [20]:
height=[174,189,18,195]
np.std(height)

73.14711204141965

In [21]:
np_height_cm=np.array(height_cm)
np_weight_lb=np.array(weight_lb)
meas=np.array([np_height_cm,np_weight_lb])
for val in meas:
    print(val)

[174 189 185 195 140 150 184 141 150 173]
[ 96  87 110 104  61 153 121 136  95 131]


In [22]:
np_height_cm=np.array(height_cm)
for x in np_height_cm:
    print(str(x)+"centimetres")

174centimetres
189centimetres
185centimetres
195centimetres
140centimetres
150centimetres
184centimetres
141centimetres
150centimetres
173centimetres


In [23]:
for val in data:
    print(val)

Gender
Height
Weight
Index


In [24]:
for lab, row in data.iterrows():
    print(lab)
    print(row)

0
Gender    Male
Height     174
Weight      96
Index        4
Name: 0, dtype: object
1
Gender    Male
Height     189
Weight      87
Index        2
Name: 1, dtype: object
2
Gender    Female
Height       185
Weight       110
Index          4
Name: 2, dtype: object
3
Gender    Female
Height       195
Weight       104
Index          3
Name: 3, dtype: object
4
Gender    Male
Height     149
Weight      61
Index        3
Name: 4, dtype: object
5
Gender    Male
Height     189
Weight     104
Index        3
Name: 5, dtype: object
6
Gender    Male
Height     147
Weight      92
Index        5
Name: 6, dtype: object
7
Gender    Male
Height     154
Weight     111
Index        5
Name: 7, dtype: object
8
Gender    Male
Height     174
Weight      90
Index        3
Name: 8, dtype: object
9
Gender    Female
Height       169
Weight       103
Index          4
Name: 9, dtype: object
10
Gender    Male
Height     195
Weight      81
Index        2
Name: 10, dtype: object
11
Gender    Female
Height       159
We

Name: 95, dtype: object
96
Gender    Male
Height     142
Weight      69
Index        4
Name: 96, dtype: object
97
Gender    Male
Height     160
Weight     139
Index        5
Name: 97, dtype: object
98
Gender    Male
Height     195
Weight      69
Index        1
Name: 98, dtype: object
99
Gender    Female
Height       190
Weight        50
Index          0
Name: 99, dtype: object
100
Gender    Male
Height     199
Weight     156
Index        4
Name: 100, dtype: object
101
Gender    Male
Height     154
Weight     105
Index        5
Name: 101, dtype: object
102
Gender    Male
Height     161
Weight     155
Index        5
Name: 102, dtype: object
103
Gender    Female
Height       198
Weight       145
Index          4
Name: 103, dtype: object
104
Gender    Female
Height       192
Weight       140
Index          4
Name: 104, dtype: object
105
Gender    Male
Height     195
Weight     126
Index        4
Name: 105, dtype: object
106
Gender    Male
Height     166
Weight     160
Index        5
Name: 

Name: 309, dtype: object
310
Gender    Male
Height     171
Weight     147
Index        5
Name: 310, dtype: object
311
Gender    Female
Height       180
Weight       156
Index          5
Name: 311, dtype: object
312
Gender    Male
Height     191
Weight     146
Index        5
Name: 312, dtype: object
313
Gender    Female
Height       179
Weight        67
Index          2
Name: 313, dtype: object
314
Gender    Female
Height       180
Weight        60
Index          2
Name: 314, dtype: object
315
Gender    Female
Height       154
Weight       132
Index          5
Name: 315, dtype: object
316
Gender    Male
Height     188
Weight      99
Index        3
Name: 316, dtype: object
317
Gender    Male
Height     142
Weight     135
Index        5
Name: 317, dtype: object
318
Gender    Male
Height     170
Weight      95
Index        4
Name: 318, dtype: object
319
Gender    Male
Height     152
Weight     141
Index        5
Name: 319, dtype: object
320
Gender    Female
Height       190
Weight       11

Name: 444, dtype: object
445
Gender    Male
Height     159
Weight     140
Index        5
Name: 445, dtype: object
446
Gender    Male
Height     146
Weight      70
Index        4
Name: 446, dtype: object
447
Gender    Female
Height       176
Weight       121
Index          4
Name: 447, dtype: object
448
Gender    Female
Height       146
Weight       101
Index          5
Name: 448, dtype: object
449
Gender    Male
Height     159
Weight     145
Index        5
Name: 449, dtype: object
450
Gender    Male
Height     162
Weight     157
Index        5
Name: 450, dtype: object
451
Gender    Female
Height       172
Weight        90
Index          4
Name: 451, dtype: object
452
Gender    Female
Height       169
Weight       121
Index          5
Name: 452, dtype: object
453
Gender    Male
Height     182
Weight      50
Index        0
Name: 453, dtype: object
454
Gender    Female
Height       183
Weight        79
Index          2
Name: 454, dtype: object
455
Gender    Male
Height     176
Weight     

In [26]:
import pandas as pd
data=pd.read_csv("500_Person_Gender_Height_Weight_Index.csv",index_col=0)
for lab, row in data.iterrows():
    print(lab +": "+ str(row["Weight"]))

Male: 96
Male: 87
Female: 110
Female: 104
Male: 61
Male: 104
Male: 92
Male: 111
Male: 90
Female: 103
Male: 81
Female: 80
Female: 101
Male: 51
Male: 79
Female: 107
Female: 110
Male: 129
Male: 145
Male: 139
Male: 110
Female: 149
Female: 97
Male: 139
Female: 67
Female: 64
Male: 95
Male: 62
Female: 159
Male: 152
Male: 121
Male: 52
Female: 65
Female: 131
Female: 153
Female: 132
Female: 114
Male: 80
Female: 152
Female: 81
Female: 120
Female: 108
Male: 56
Male: 118
Female: 126
Male: 76
Female: 122
Male: 111
Male: 72
Male: 152
Female: 135
Female: 54
Male: 110
Male: 105
Male: 116
Female: 89
Male: 92
Male: 127
Female: 70
Male: 88
Female: 54
Female: 143
Male: 54
Male: 83
Male: 135
Female: 158
Female: 96
Female: 59
Female: 82
Female: 136
Female: 51
Male: 117
Male: 80
Male: 75
Female: 100
Female: 154
Male: 104
Female: 90
Female: 122
Male: 51
Male: 75
Female: 140
Female: 105
Male: 118
Male: 123
Male: 50
Female: 141
Male: 117
Female: 104
Female: 140
Female: 154
Female: 96
Female: 111
Male: 61
Male: 1